### ISSUE TITLE
ModuleNotFoundError: No module named 'd src'

### ISSUE THREAD

**Issue by aktaseren** [harsh2912/people-tracking#6]
Hi @harsh2912, thank you for making this repo available. As you suggest, I followed the installation and then I wanted to test a video downloaded through the repo. 

When I run the line below: 

`(FairMOT) 455832@soc-MBP1320-EA src % python script.py -mp /Users/455832/people-tracking/experiments/all_dla34.sh -vp /Users/455832/people-tracking/videos/MOT16-03.mp4 -od /Users/455832/people-tracking/videos/`

I am having the issue below:

`Traceback (most recent call last):
  File "script.py", line 23, in <module>
    eval_seq(opt, dl, 'mot',save_dir=output_dir, show_image=show_image)
  File "/Users/455832/people-tracking/src/track.py", line 42, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "/Users/455832/people-tracking/src/lib/tracker/multitracker.py", line 176, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "/Users/455832/people-tracking/src/lib/models/model.py", line 31, in load_model
    checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "/Users/455832/opt/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/455832/opt/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
ModuleNotFoundError: No module named 'd src'`

Can you please suggest to me how to solve this issue?

**Comment by aktaseren** [comment]
Sorry it was a silly issue that I overlooked. located the model wrong in the line.
